accountLinking:
  appClientId: jovopoc
  authGrantType: AUTH_CODE
  authorizationUrl: https://100032668.auth.konycloud.com/oidc/authorize/IronBankOauth2
  linkingType: OAUTH
  scopes:
  - openid
  - email
  - profile
  - phone
  - offline_access
  tokenUrl: https://tpko-dev.konycloud.com/services/Oauth2Token/token
  useBasicAuthHeader: true
defaultLocale: en
localizedSettings:
  displayName: iron bank
  pronunciation: iron bank
projectId: jovopoc
testingInstructions: |-
  user@foo.com
  Pw!123456
